### Loading the models

In [3]:
import numpy as np
import pandas as pd
import tensorflow as tf
import pickle
from tensorflow.keras.models import load_model

In [4]:
### load the trained model
model = load_model('model.h5')

## load encoder and scaler

with open('label_encoder_gender.pkl', 'rb') as file:
    label_encoder_gender= pickle.load(file)


with open('onehot_encoder_geo.pkl','rb') as file:
    label_encoder_geo= pickle.load(file)

with open('scaler.pkl','rb') as file:
    scaler=pickle.load(file)

WARNING:tensorflow:TensorFlow GPU support is not available on native Windows for TensorFlow >= 2.11. Even if CUDA/cuDNN are installed, GPU will not be used. Please use WSL2 or the TensorFlow-DirectML plugin.

WARNING:absl:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

In [5]:
## Example input file
input_data = {
    'CreditScore': 600,
    'Geography': 'France',
    'Gender': 'Male',
    'Age': 40,
    'Tenure': 3,
    'Balance': 60000,
    'NumOfProducts': 2,
    'HasCrCard': 1,
    'IsActiveMember': 1,
    'EstimatedSalary': 50000
}

In [6]:
## one hot encode geography
geo_encoded = label_encoder_geo.transform([[input_data['Geography']]]).toarray()
geo_encoded_df = pd.DataFrame(geo_encoded, columns=label_encoder_geo.get_feature_names_out(['Geography']))
geo_encoded_df

c:\Users\Hp\.conda\envs\envANN\Lib\site-packages\sklearn\utils\validation.py:2827: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(

   Geography_France  Geography_Germany  Geography_Spain
0               1.0                0.0              0.0

In [7]:
## convert the input data to data frame 
input_df = pd.DataFrame([input_data])
input_df

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
0,600,France,Male,40,3,60000,2,1,1,50000

In [8]:
### Encode categorical varible - gender
input_df['Gender'] = label_encoder_gender.transform(input_df['Gender'])
input_df

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
0,600,France,1,40,3,60000,2,1,1,50000

In [9]:
##  Combine the one hot encoded columns with input data
input_df = pd.concat([input_df.drop('Geography', axis=1), geo_encoded_df], axis=1)
input_df

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Geography_France,Geography_Germany,Geography_Spain
0,600,1,40,3,60000,2,1,1,50000,1.0,0.0,0.0

In [10]:
## Scaling the input data
input_scaled = scaler.transform(input_df)
input_scaled

array([[-0.53598516,  0.91324755,  0.10479359, -0.69539349, -0.25781119,
         0.80843615,  0.64920267,  0.97481699, -0.87683221,  1.00150113,
        -0.57946723, -0.57638802]])

In [14]:
### prediction - checking if customer is existed or not
prediction = model.predict(input_scaled)
prediction

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 99ms/step

array([[0.04225564]], dtype=float32)

In [17]:
#prediction probability

prediction_probability = prediction[0][0]
prediction_probability

np.float32(0.04225564)

In [18]:
if prediction_probability > 0.5:
    print("custmer is likely to churn")
else:
    print("customer is not likely to churn")

customer is not likely to churn

In [ ]:
# just for knowledge 
# label_encoder_gender.classes_

array(['Female', 'Male'], dtype=object)

In [24]:
label_encoder_geo.categories_

[array(['France', 'Germany', 'Spain'], dtype=object)]

In [25]:
 label_encoder_geo.categories_[0]

array(['France', 'Germany', 'Spain'], dtype=object)